- name: 创建GitHub Release
  id: create_release
  uses: actions/create-release@latest
	with:
    tag_name: v${{steps.version.outputs.value}}
    release_name: v${{steps.version.outputs.value}}
    body: ${{steps.description.outputs.content}}
    draft: false
    prerelease: false
